const ALERT = "ALERT";

const REFETCH_CHATS = "REFETCH_CHATS";

const NEW_ATTACHMENT = "NEW_ATTACHMENT";

const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";

const NEW_REQUEST = "NEW_REQUEST";

const NEW_MESSAGE = "NEW_MESSAGE";

const START_TYPING = "START_TYPING";

const STOP_TYPING = "STOP_TYPING";

const UPDATE_LOCATION = "UPDATE_LOCATION";

const FRIEND_LOCATION = "FRIEND_LOCATION";

const CHAT_JOINED = "CHAT_JOINED";

const CHAT_LEFT = "CHAT_LEFT";

const ONLINE_USER = "ONLINE_USER";

export {
  ALERT,
  REFETCH_CHATS,
  NEW_ATTACHMENT,
  NEW_MESSAGE_ALERT,
  NEW_REQUEST,
  NEW_MESSAGE,
  START_TYPING,
  STOP_TYPING,
  UPDATE_LOCATION,
  FRIEND_LOCATION,
  CHAT_JOINED,
  CHAT_LEFT,
  ONLINE_USER,
 
};
